### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by vlee489** [BareConductive/touch-usb-midi-interface#1]
I don't know too much about Arduino but i keep getting this error code 

> Midi_interface.ino:29:1: error: 'MIDIEvent' does not name a type
> Midi_interface.ino: In function 'void setup()':
> Midi_interface.ino:37:3: error: 'e' was not declared in this scope
> Midi_interface.ino: In function 'void loop()':
> Midi_interface.ino:49:7: error: 'e' was not declared in this scope
> Midi_interface.ino:67:9: error: 'MIDIUSB' was not declared in this scope
> Midi_interface.ino:71:5: error: 'MIDIUSB' was not declared in this scope

**Comment by stefandz** [comment]
Hi Vlee

I don't think that you have installed ARcore correctly, or you haven't selected the correct board in the Arduino menu. Check out our guide here - http://www.bareconductive.com/make/midi-interface/

S

**Comment by vlee489** [comment]
I have arcore-master installed properly.

**Comment by vlee489** [comment]
I seem not to have "Bare Conductive Touch Board (arcore, iPad Compatible)" as a option

**Comment by stefandz** [comment]
Thanks for your response, Vincent. If you have it correctly installed, then
you should be able to see "Bare Conductive Touch Board (arcore, iPad
compatible)" in the Arduino Tools -> Board menu. Selecting that will solve
your issue.

If, however, you can't see this, then Arcore is not correctly installed. In
this case, please follow all of the instructions in the tutorial I linked
in before.

S

**Comment by vlee489** [comment]
I've just reinstalled all the stuff but now 

> Selected board depends on 'arduino' core (not installed)

**Comment by vlee489** [comment]
fixed it. but the Bare Conductive mid install instructions don't work

**Comment by stefandz** [comment]
Thanks for all your replies, Vincent. Which step of the install
instructions do you think needs changing? It would be great if you could
point it out so we can save others the effort you have had to go through!

Many thanks

Stefan

**Comment by stefandz** [comment]
And also, what did you have to do to fix it?

S

**Comment by vlee489** [comment]
Give me a day as I don't have school tomorrow and I'll do a full guide on how to do it.

**Comment by stefandz** [comment]
Wow, that would be great, thanks!

S

**Comment by vlee489** [comment]
Now Just looking back its just 1 problems in the instructions that need to be fixed. 

> For Arcore-master.zip the 2 folders in the hardware folder need to be in the put into the hardware. folder,adding the arcore-master folder itself won't do.

This should fix the problem but double check if I'm right just in case.

Edit: I would do a full write up but it's a small problem and I'm too tired/Lazy

**Comment by stefandz** [comment]
No worries, thanks for the comments so far - I'll add these to the existing instructions. Thanks for your help!

**Comment by skialta** [comment]
I ran into this same problem. Although I had downloaded the new version of Arduino, I was still opening the old one. Problem fixed when I started using Arduino 1.6.
