### ISSUE TITLE
error message when trying to upload code

### ISSUE THREAD

**Issue by arneborgan** [BareConductive/touch-usb-midi-interface#2]
Hi 
I get this message:
Arduino:1.6.0 (Mac OS X), Kort"Bare Conductive Touch Board (USB MIDI, iPad compatible)"

Using library MPR121 in folder: /Users/arne/Documents/Arduino/libraries/MPR121 (legacy)
Using library Wire in folder: /Users/arne/Documents/Arduino/hardware/bare_conductive_arduino/avr/libraries/Wire 

{runtime.tools.avr-gcc.path}/bin/avr-g++ -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10600 -DARDUINO_AVR_BARETOUCH -DARDUINO_ARCH_AVR -DUSB_VID=0x2A6E -DUSB_PID=0x8003 -DIPAD_COMPAT -I/Users/arne/Documents/Arduino/hardware/bare_conductive_arduino/avr/cores/arcore -I/Applications/___Lydprogram/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/variants/leonardo -I/Users/arne/Documents/Arduino/libraries/MPR121 -I/Users/arne/Documents/Arduino/hardware/bare_conductive_arduino/avr/libraries/Wire /var/folders/I3/I3HVUyo7EjWcz584D4sGxk+++TI/-Tmp-/build4616597089864548988.tmp/Midi_interface.cpp -o /var/folders/I3/I3HVUyo7EjWcz584D4sGxk+++TI/-Tmp-/build4616597089864548988.tmp/Midi_interface.cpp.o 
Cannot run program "{runtime.tools.avr-gcc.path}/bin/avr-g++": error=2, No such file or directory

**Comment by stefandz** [comment]
Hi - could you try this again with Arduino 1.6.5?

**Comment by stefandz** [comment]
I've double-checked and this should be fine in Arduino 1.6.4 and later. We're in the process of updating all our code sources to be 1.6.6 compatible which will break backwards compatibility in any case, so I am closing this for now. Let me know if you are still having issues, and in the future we will be supporting 1.6.6+ only.
