### ISSUE TITLE
can't select MIDI channel

### ISSUE THREAD

**Issue by mickeyvanolst** [BareConductive/touch-usb-midi-interface#3]
Hi guys, I've done quite some digging, but can't find any way of setting the MIDI channel at which this thing writes. It's currently set to 1, I'd like to be able to set it to 3 in order to talk to Teenage Engineerings OP-1

**Comment by stefandz** [comment]
Hey - thanks for raising this. It's not really clear from the example code - we've never had anyone want to use a separate channel. As you can see here: http://www.midi.org/techspecs/midimessages.php the bottom 4 bits of the first byte of a MIDI message encode the channel number from 0 (which I think you're calling 1) to 15 (16 in your numbering scheme).

For your example, you should be able to achieve what you want my changing line 58 of Midi_interface.ino to read:

```
e.m1 = 0x92; 
```

and line 63 to read:

```
e.m1 = 0x82;
```

Let me know how you get on with this - I'll leave this issue open for now to remind me to commit some tested expansion code for this. Also, do let us know what you're making with the OP-1 - lovely bit of kit! Feel free to email updates to info@bareconductive.com - we love seeing what people get up to with the Touch Board.

**Comment by mickeyvanolst** [comment]
amazing response! Works like a doozy. Still have some cable things to sort out to get it working directly, but I can see the right channel coming in on my laptop and can simply forward it to the connected OP-1. Thanks for the quick update.

**Comment by mickeyvanolst** [comment]
its intended as an example for a workshop I'm giving, things are a bit open so who knows what it will turn into ;-) will try to snap some photos in the mean time

**Comment by stefandz** [comment]
Thanks - would be great to see! Glad it is working well for you. Will definitely include this feature in the next version of this code.
